#!/bin/bash
# gen_test_certs.sh — Generate P-384 ECDSA test certificate chain for mTLS demo.
#
# Output:
#   certs/ca-cert.pem, certs/ca-key.pem         — Root CA
#   certs/server-cert.pem, certs/server-key.pem  — Server cert (CN=localhost)
#   certs/client-cert.pem, certs/client-key.pem  — Client cert (CN=stm32u385-demo)
#   src/certs_gen.h                              — C arrays for embedded use (DER)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TOP="$(dirname "$SCRIPT_DIR")"
CERT_DIR="$TOP/certs"
OUT_H="$TOP/src/certs_gen.h"

mkdir -p "$CERT_DIR"

echo "=== Generating P-384 ECDSA test certificates ==="

# --- Root CA ---
openssl ecparam -genkey -name secp384r1 -noout -out "$CERT_DIR/ca-key.pem"
openssl req -new -x509 -key "$CERT_DIR/ca-key.pem" \
    -out "$CERT_DIR/ca-cert.pem" -days 3650 \
    -subj "/CN=wolfMQTT Test CA/O=wolfSSL/C=US" \
    -sha384

# --- Server cert ---
openssl ecparam -genkey -name secp384r1 -noout -out "$CERT_DIR/server-key.pem"
openssl req -new -key "$CERT_DIR/server-key.pem" \
    -out "$CERT_DIR/server.csr" \
    -subj "/CN=localhost/O=wolfSSL/C=US"

cat > "$CERT_DIR/server-ext.cnf" <<SEOF
basicConstraints=CA:FALSE
subjectAltName=DNS:localhost,IP:127.0.0.1
SEOF

openssl x509 -req -in "$CERT_DIR/server.csr" \
    -CA "$CERT_DIR/ca-cert.pem" -CAkey "$CERT_DIR/ca-key.pem" \
    -CAcreateserial -out "$CERT_DIR/server-cert.pem" -days 3650 \
    -sha384 -extfile "$CERT_DIR/server-ext.cnf"

# --- Client cert ---
openssl ecparam -genkey -name secp384r1 -noout -out "$CERT_DIR/client-key.pem"
openssl req -new -key "$CERT_DIR/client-key.pem" \
    -out "$CERT_DIR/client.csr" \
    -subj "/CN=stm32u385-demo/O=wolfSSL/C=US"

cat > "$CERT_DIR/client-ext.cnf" <<CEOF
basicConstraints=CA:FALSE
keyUsage=digitalSignature
extendedKeyUsage=clientAuth
CEOF

openssl x509 -req -in "$CERT_DIR/client.csr" \
    -CA "$CERT_DIR/ca-cert.pem" -CAkey "$CERT_DIR/ca-key.pem" \
    -CAcreateserial -out "$CERT_DIR/client-cert.pem" -days 3650 \
    -sha384 -extfile "$CERT_DIR/client-ext.cnf"

# --- Convert to DER for embedding ---
openssl x509 -in "$CERT_DIR/ca-cert.pem" -outform DER -out "$CERT_DIR/ca-cert.der"
openssl x509 -in "$CERT_DIR/client-cert.pem" -outform DER -out "$CERT_DIR/client-cert.der"
openssl ec -in "$CERT_DIR/client-key.pem" -outform DER -out "$CERT_DIR/client-key.der"

# --- Generate C header with properly named arrays ---
{
    echo "/* Auto-generated by gen_test_certs.sh — do not edit. */"
    echo "/*"
    echo " * !!  TEST KEYS ONLY  !!"
    echo " *"
    echo " * The arrays below contain a P-384 private key and matching"
    echo " * certificates generated locally by this script. They are for"
    echo " * the wolfMQTT demo only — NEVER copy these bytes into"
    echo " * production code. Do not commit this file to source control"
    echo " * (it is in .gitignore for a reason)."
    echo " */"
    echo "#ifndef DEMO_CERTS_GEN_H"
    echo "#define DEMO_CERTS_GEN_H"
    echo ""

    for pair in "ca-cert.der:demo_ca_cert" "client-cert.der:demo_cli_cert" "client-key.der:demo_cli_key"; do
        file="${pair%%:*}"
        var="${pair##*:}"
        size=$(wc -c < "$CERT_DIR/$file")
        echo "/* $file ($size bytes) */"
        echo "static const unsigned char ${var}[] = {"
        xxd -i < "$CERT_DIR/$file" | sed 's/^/    /'
        echo "};"
        echo "#define ${var}_size sizeof(${var})"
        echo ""
    done

    echo "#endif /* DEMO_CERTS_GEN_H */"
} > "$OUT_H"

echo "=== Done. Cert files in $CERT_DIR, C header at $OUT_H ==="
