/* certs.h
 *
 * Copyright (C) 2006-2026 wolfSSL Inc.
 *
 * This file is part of wolfSSL.
 *
 * wolfSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

/*
 * Certificate aliases for the MQTT mTLS demo.
 * Uses P-384 ECDSA certs generated by host/gen_test_certs.sh.
 * If certs_gen.h is missing, run the script first.
 */
#ifndef DEMO_CERTS_H
#define DEMO_CERTS_H

#include "certs_gen.h"

/* Aliases used by main.c (WOLFMQTT_DEMO) — DER format */
#define DEMO_CA_CERT_BUF    demo_ca_cert
#define DEMO_CA_CERT_SIZE   demo_ca_cert_size

#define DEMO_CLI_CERT_BUF   demo_cli_cert
#define DEMO_CLI_CERT_SIZE  demo_cli_cert_size

#define DEMO_CLI_KEY_BUF    demo_cli_key
#define DEMO_CLI_KEY_SIZE   demo_cli_key_size

#endif /* DEMO_CERTS_H */
